
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 17 01:03:06 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 34;
  public static final int CONST = 27;
  public static final int LPAREN = 13;
  public static final int SEMI = 5;
  public static final int L = 23;
  public static final int NUM_CONST = 33;
  public static final int MINUS = 19;
  public static final int G = 22;
  public static final int RPAREN = 14;
  public static final int COMMA = 6;
  public static final int INC = 10;
  public static final int DIV = 16;
  public static final int GEQ = 24;
  public static final int PLUS = 18;
  public static final int EOF = 0;
  public static final int EQUAL = 7;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int MOD = 17;
  public static final int IDENT = 32;
  public static final int VOID = 28;
  public static final int NOTSAME = 21;
  public static final int COLON = 12;
  public static final int SAME = 20;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 8;
  public static final int READ = 29;
  public static final int GOTO = 31;
  public static final int RSQUARE = 9;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int LEQ = 25;
  public static final int BOOL_CONST = 35;
  public static final int DEC = 11;
  public static final int PRINT = 30;
}

